### ISSUE TITLE
intent: debug showing sometimes

### ISSUE THREAD

**Issue by fastfinge** [Wensber/TextTheSpire#1]
I haven't been able to find a pattern to this, but a few times (especially seems to be when fighting multiple monsters), the monster window shows something like this:

Count: 3
Incoming: 0
0: Louse
Block: 0
HP: 12/12
Intent: Debug (Shouldn't Happen)
Powers:
0: Curl Up 6

1: Louse
Block: 0
HP: 12/12
Intent: Debug (Shouldn't Happen)
Powers:
0: Curl Up 3

2: Louse
Block: 0
HP: 15/15
Intent: Debug (Shouldn't Happen)
Powers:
0: Curl Up 5

Other times it works just fine, on the same run.  Is there any logging or anything I can enable to help us get more insight on this?

**Comment by Wensber** [comment]
Hello.

Someone else also mentioned this and I think I know what's going on.

I assume this is happening at the very beginning of a fight or turn and you
are using prompt and output rather than looking at the monster window.

An enemy's intent is debug before it is initialized and you are just a
little early. The monster window would auto update when intent changes.

If this is the case then there isn't much I can do about it as I can't read
the intent if its not there yet.

Thanks,
Wensber

**Comment by fastfinge** [comment]
Yup, after some more testing, that's exactly what's happening.  If I wait until the monster sound finishes I don't have this problem.  Thanks!
